#!/bin/bash
# Generated by cmake 
# Following is the extra envvar:

export CEPCSW_ROOT=/publicfs/cms/user/wanghan/CEPCSW

export DETCEPCV4ROOT=/publicfs/cms/user/wanghan/CEPCSW/Detector/DetCEPCv4
export DETCRDROOT=/publicfs/cms/user/wanghan/CEPCSW/Detector/DetCRD
export DETDRIFTCHAMBERROOT=/publicfs/cms/user/wanghan/CEPCSW/Detector/DetDriftChamber

